version = "0.6.0"

[settings]
mode = "branch"
prompt = "never"
prompt_prefixes = [
    "feature",
    "release",
]

[sync]
monorepo = "lockstep"
constants = "curated"
exclude = []

[prefixes]
feature = "minor"
fix = "patch"
release = "major"

[release]
enabled = true
on_bump = []
match = ""
skip = ""

[changelog]
enabled = true
on_bump = []
template = "conventional"
